///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyAssaysApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Endpoint_Absorbance_OD_ recording.
    /// </summary>
    [TestModule("07867a42-07af-4ff7-a357-ce0553a04c36", ModuleType.Recording, 1)]
    public partial class Endpoint_Absorbance_OD_ : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyAssaysAppRepository repository.
        /// </summary>
        public static MyAssaysAppRepository repo = MyAssaysAppRepository.Instance;

        static Endpoint_Absorbance_OD_ instance = new Endpoint_Absorbance_OD_();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Endpoint_Absorbance_OD_()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Endpoint_Absorbance_OD_ Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Program Files (x86)\\MyAssays\\MyAssays Desktop\\MyAssays.Desktop.Explorer.exe' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Program Files (x86)\\MyAssays\\MyAssays Desktop\\MyAssays.Desktop.Explorer.exe", "", "C:\\Program Files (x86)\\MyAssays\\MyAssays Desktop", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'NewProtocolWizard1.MyMeasurementDataIs'.", repo.NewProtocolWizard1.MyMeasurementDataIsInfo, new RecordItemIndex(1));
            Validate.Attribute(repo.NewProtocolWizard1.MyMeasurementDataIsInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='My measurement data is:') on item 'NewProtocolWizard1.MyMeasurementDataIs'.", repo.NewProtocolWizard1.MyMeasurementDataIsInfo, new RecordItemIndex(2));
            Validate.Attribute(repo.NewProtocolWizard1.MyMeasurementDataIsInfo, "Text", "My measurement data is:");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'NewProtocolWizard1.DetectionTechnology'.", repo.NewProtocolWizard1.DetectionTechnologyInfo, new RecordItemIndex(3));
            Validate.Attribute(repo.NewProtocolWizard1.DetectionTechnologyInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Detection technology:') on item 'NewProtocolWizard1.DetectionTechnology'.", repo.NewProtocolWizard1.DetectionTechnologyInfo, new RecordItemIndex(4));
            Validate.Attribute(repo.NewProtocolWizard1.DetectionTechnologyInfo, "Text", "Detection technology:");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'NewProtocolWizard1.ListView2.ListView'.", repo.NewProtocolWizard1.ListView2.ListViewInfo, new RecordItemIndex(5));
            Validate.Attribute(repo.NewProtocolWizard1.ListView2.ListViewInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (SelectedItemText='MyAssays.Desktop.ProtocolWizard.ViewModels.DataTypeStepViewModel+MeasurementsTypeDescription') on item 'NewProtocolWizard1.ListView2.ListView'.", repo.NewProtocolWizard1.ListView2.ListViewInfo, new RecordItemIndex(6));
            Validate.Attribute(repo.NewProtocolWizard1.ListView2.ListViewInfo, "SelectedItemText", "MyAssays.Desktop.ProtocolWizard.ViewModels.DataTypeStepViewModel+MeasurementsTypeDescription");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'NewProtocolWizard1.ListView1'.", repo.NewProtocolWizard1.ListView1Info, new RecordItemIndex(7));
            Validate.Attribute(repo.NewProtocolWizard1.ListView1Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (SelectedItemText='MyAssays.Data.Xml.ProtocolWizardSettingsTechnology') on item 'NewProtocolWizard1.ListView1'.", repo.NewProtocolWizard1.ListView1Info, new RecordItemIndex(8));
            Validate.Attribute(repo.NewProtocolWizard1.ListView1Info, "SelectedItemText", "MyAssays.Data.Xml.ProtocolWizardSettingsTechnology");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard1.ListView2.Endpoint' at Center.", repo.NewProtocolWizard1.ListView2.EndpointInfo, new RecordItemIndex(9));
            repo.NewProtocolWizard1.ListView2.Endpoint.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard1.AbsorbanceOD' at Center.", repo.NewProtocolWizard1.AbsorbanceODInfo, new RecordItemIndex(10));
            repo.NewProtocolWizard1.AbsorbanceOD.Click();
            Delay.Milliseconds(200);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.NewProtocolWizard1.DataTypeStepControl, false, new RecordItemIndex(11));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'NewProtocolWizard1.Back'.", repo.NewProtocolWizard1.BackInfo, new RecordItemIndex(12));
            Validate.Attribute(repo.NewProtocolWizard1.BackInfo, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'NewProtocolWizard1.Next'.", repo.NewProtocolWizard1.NextInfo, new RecordItemIndex(13));
            Validate.Attribute(repo.NewProtocolWizard1.NextInfo, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard1.Next1' at Center.", repo.NewProtocolWizard1.Next1Info, new RecordItemIndex(14));
            repo.NewProtocolWizard1.Next1.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
