///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyAssaysApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FormatPadPlate recording.
    /// </summary>
    [TestModule("9433a209-fddb-4a3b-8d39-723657e4d718", ModuleType.Recording, 1)]
    public partial class FormatPadPlate : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyAssaysAppRepository repository.
        /// </summary>
        public static MyAssaysAppRepository repo = MyAssaysAppRepository.Instance;

        static FormatPadPlate instance = new FormatPadPlate();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FormatPadPlate()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FormatPadPlate Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Program Files (x86)\\MyAssays\\MyAssays Desktop\\MyAssays.Desktop.Explorer.exe' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Program Files (x86)\\MyAssays\\MyAssays Desktop\\MyAssays.Desktop.Explorer.exe", "", "C:\\Program Files (x86)\\MyAssays\\MyAssays Desktop", false);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Provide your measurement data following the format illustrated by the example data.') on item 'NewProtocolWizard.SomeContainer.ProvideYourMeasurementDataFollowing'.", repo.NewProtocolWizard.SomeContainer.ProvideYourMeasurementDataFollowingInfo, new RecordItemIndex(1));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer.ProvideYourMeasurementDataFollowingInfo, "Text", "Provide your measurement data following the format illustrated by the example data.");
            Delay.Milliseconds(100);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Text='Paste') on item 'NewProtocolWizard.MultipleContainerViewPanel.PasteButton'.", repo.NewProtocolWizard.MultipleContainerViewPanel.PasteButtonInfo, new RecordItemIndex(2));
                Validate.Attribute(repo.NewProtocolWizard.MultipleContainerViewPanel.PasteButtonInfo, "Text", "Paste", Validate.DefaultMessage, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Clear') on item 'NewProtocolWizard.MultipleContainerViewPanel.ClearButton'.", repo.NewProtocolWizard.MultipleContainerViewPanel.ClearButtonInfo, new RecordItemIndex(3));
            Validate.Attribute(repo.NewProtocolWizard.MultipleContainerViewPanel.ClearButtonInfo, "Text", "Clear");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='False') on item 'NewProtocolWizard.MultipleContainerViewPanel.DataFormatToggleButton'.", repo.NewProtocolWizard.MultipleContainerViewPanel.DataFormatToggleButtonInfo, new RecordItemIndex(4));
            Validate.Attribute(repo.NewProtocolWizard.MultipleContainerViewPanel.DataFormatToggleButtonInfo, "Checked", "False");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.MultipleContainerViewPanel.DataFormatToggleButton' at Center.", repo.NewProtocolWizard.MultipleContainerViewPanel.DataFormatToggleButtonInfo, new RecordItemIndex(5));
            repo.NewProtocolWizard.MultipleContainerViewPanel.DataFormatToggleButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Decimal separator:') on item 'NewProtocolWizard.MultipleContainerViewPanel.DecimalSeparator'.", repo.NewProtocolWizard.MultipleContainerViewPanel.DecimalSeparatorInfo, new RecordItemIndex(6));
            Validate.Attribute(repo.NewProtocolWizard.MultipleContainerViewPanel.DecimalSeparatorInfo, "Text", "Decimal separator:");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='System Default') on item 'NewProtocolWizard.MultipleContainerViewPanel.DecimalSeparatorComboBox'.", repo.NewProtocolWizard.MultipleContainerViewPanel.DecimalSeparatorComboBoxInfo, new RecordItemIndex(7));
            Validate.Attribute(repo.NewProtocolWizard.MultipleContainerViewPanel.DecimalSeparatorComboBoxInfo, "Text", "System Default");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.MultipleContainerViewPanel.DecimalSeparatorComboBox' at LowerCenter.", repo.NewProtocolWizard.MultipleContainerViewPanel.DecimalSeparatorComboBoxInfo, new RecordItemIndex(8));
            repo.NewProtocolWizard.MultipleContainerViewPanel.DecimalSeparatorComboBox.Click(Location.LowerCenter);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysDesktopExplorer.Comma' at Center.", repo.MyAssaysDesktopExplorer.CommaInfo, new RecordItemIndex(9));
            repo.MyAssaysDesktopExplorer.Comma.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.MultipleContainerViewPanel.DecimalSeparatorComboBox' at Center.", repo.NewProtocolWizard.MultipleContainerViewPanel.DecimalSeparatorComboBoxInfo, new RecordItemIndex(10));
            repo.NewProtocolWizard.MultipleContainerViewPanel.DecimalSeparatorComboBox.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysDesktopExplorer.Period' at Center.", repo.MyAssaysDesktopExplorer.PeriodInfo, new RecordItemIndex(11));
            repo.MyAssaysDesktopExplorer.Period.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.MultipleContainerViewPanel.DecimalSeparatorComboBox' at Center.", repo.NewProtocolWizard.MultipleContainerViewPanel.DecimalSeparatorComboBoxInfo, new RecordItemIndex(12));
            repo.NewProtocolWizard.MultipleContainerViewPanel.DecimalSeparatorComboBox.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysDesktopExplorer.SystemDefault' at Center.", repo.MyAssaysDesktopExplorer.SystemDefaultInfo, new RecordItemIndex(13));
            repo.MyAssaysDesktopExplorer.SystemDefault.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.MultipleContainerViewPanel.DataFormatToggleButton' at Center.", repo.NewProtocolWizard.MultipleContainerViewPanel.DataFormatToggleButtonInfo, new RecordItemIndex(14));
            repo.NewProtocolWizard.MultipleContainerViewPanel.DataFormatToggleButton.Click();
            Delay.Milliseconds(200);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.NewProtocolWizard.MultipleContainerViewPanel.Self, false, new RecordItemIndex(15));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'NewProtocolWizard.SomeContainer.TabPagePad'.", repo.NewProtocolWizard.SomeContainer.TabPagePadInfo, new RecordItemIndex(16));
            Validate.Exists(repo.NewProtocolWizard.SomeContainer.TabPagePadInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'NewProtocolWizard.MultipleContainerViewPanel.SomeElement'.", repo.NewProtocolWizard.MultipleContainerViewPanel.SomeElementInfo, new RecordItemIndex(17));
            Validate.Exists(repo.NewProtocolWizard.MultipleContainerViewPanel.SomeElementInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer.EndpointGridTab' at Center.", repo.NewProtocolWizard.SomeContainer.EndpointGridTabInfo, new RecordItemIndex(18));
            repo.NewProtocolWizard.SomeContainer.EndpointGridTab.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'NewProtocolWizard.SomeContainer.EndpointGridTab'.", repo.NewProtocolWizard.SomeContainer.EndpointGridTabInfo, new RecordItemIndex(19));
            Validate.Exists(repo.NewProtocolWizard.SomeContainer.EndpointGridTabInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'NewProtocolWizard.SomeElement'.", repo.NewProtocolWizard.SomeElementInfo, new RecordItemIndex(20));
            Validate.Exists(repo.NewProtocolWizard.SomeElementInfo);
            Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.NewProtocolWizard.MultipleContainerViewPanel.Self, false, new RecordItemIndex(21));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Valid='True') on item 'NewProtocolWizard.SomeContainer.Next1'.", repo.NewProtocolWizard.SomeContainer.Next1Info, new RecordItemIndex(22));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer.Next1Info, "Valid", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer.Next1' at Center.", repo.NewProtocolWizard.SomeContainer.Next1Info, new RecordItemIndex(23));
            repo.NewProtocolWizard.SomeContainer.Next1.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
