///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyAssaysApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ManageTypes recording.
    /// </summary>
    [TestModule("6fea5233-fc64-4207-bbae-f0f572f7233a", ModuleType.Recording, 1)]
    public partial class ManageTypes : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyAssaysAppRepository repository.
        /// </summary>
        public static MyAssaysAppRepository repo = MyAssaysAppRepository.Instance;

        static ManageTypes instance = new ManageTypes();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ManageTypes()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ManageTypes Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Program Files (x86)\\MyAssays\\MyAssays Desktop\\MyAssays.Desktop.Explorer.exe' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Program Files (x86)\\MyAssays\\MyAssays Desktop\\MyAssays.Desktop.Explorer.exe", "", "C:\\Program Files (x86)\\MyAssays\\MyAssays Desktop", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer.Back' at Center.", repo.NewProtocolWizard.SomeContainer.BackInfo, new RecordItemIndex(1));
            repo.NewProtocolWizard.SomeContainer.Back.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer.AdvancedViewButton' at Center.", repo.NewProtocolWizard.SomeContainer.AdvancedViewButtonInfo, new RecordItemIndex(2));
            repo.NewProtocolWizard.SomeContainer.AdvancedViewButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SampleTypesEditor.SomeContainer.AddSampleType' at Center.", repo.SampleTypesEditor.SomeContainer.AddSampleTypeInfo, new RecordItemIndex(3));
            repo.SampleTypesEditor.SomeContainer.AddSampleType.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SampleTypesEditor.SomeContainer.AddSampleType' at Center.", repo.SampleTypesEditor.SomeContainer.AddSampleTypeInfo, new RecordItemIndex(4));
            repo.SampleTypesEditor.SomeContainer.AddSampleType.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SampleTypesEditor.SomeContainer.AddSampleType' at Center.", repo.SampleTypesEditor.SomeContainer.AddSampleTypeInfo, new RecordItemIndex(5));
            repo.SampleTypesEditor.SomeContainer.AddSampleType.Click();
            Delay.Milliseconds(200);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.SampleTypesEditor.SomeContainer.Self, false, new RecordItemIndex(6));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'SampleTypesEditor.SomeContainer1.SampleType29'.", repo.SampleTypesEditor.SomeContainer1.SampleType29Info, new RecordItemIndex(7));
            Validate.Attribute(repo.SampleTypesEditor.SomeContainer1.SampleType29Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='SampleType29') on item 'SampleTypesEditor.SomeContainer1.SampleType29'.", repo.SampleTypesEditor.SomeContainer1.SampleType29Info, new RecordItemIndex(8));
            Validate.Attribute(repo.SampleTypesEditor.SomeContainer1.SampleType29Info, "Text", "SampleType29");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'SampleTypesEditor.SomeContainer1.ToggleButton1'.", repo.SampleTypesEditor.SomeContainer1.ToggleButton1Info, new RecordItemIndex(9));
            Validate.Attribute(repo.SampleTypesEditor.SomeContainer1.ToggleButton1Info, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'SampleTypesEditor.SomeContainer1.ToggleButton1'.", repo.SampleTypesEditor.SomeContainer1.ToggleButton1Info, new RecordItemIndex(10));
            Validate.Attribute(repo.SampleTypesEditor.SomeContainer1.ToggleButton1Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='False') on item 'SampleTypesEditor.SomeContainer1.ToggleButton1'.", repo.SampleTypesEditor.SomeContainer1.ToggleButton1Info, new RecordItemIndex(11));
            Validate.Attribute(repo.SampleTypesEditor.SomeContainer1.ToggleButton1Info, "Checked", "False");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'SampleTypesEditor.SomeContainer.SomeContainer'.", repo.SampleTypesEditor.SomeContainer.SomeContainerInfo, new RecordItemIndex(12));
            Validate.Attribute(repo.SampleTypesEditor.SomeContainer.SomeContainerInfo, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'SampleTypesEditor.SomeContainer.SomeContainer'.", repo.SampleTypesEditor.SomeContainer.SomeContainerInfo, new RecordItemIndex(13));
            Validate.Attribute(repo.SampleTypesEditor.SomeContainer.SomeContainerInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'SampleTypesEditor.SomeContainer1.SomeButton1'.", repo.SampleTypesEditor.SomeContainer1.SomeButton1Info, new RecordItemIndex(14));
            Validate.Attribute(repo.SampleTypesEditor.SomeContainer1.SomeButton1Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SampleTypesEditor.SomeContainer1.ToggleButton1' at Center.", repo.SampleTypesEditor.SomeContainer1.ToggleButton1Info, new RecordItemIndex(15));
            repo.SampleTypesEditor.SomeContainer1.ToggleButton1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysDesktopExplorer.Calibrator' at Center.", repo.MyAssaysDesktopExplorer.CalibratorInfo, new RecordItemIndex(16));
            repo.MyAssaysDesktopExplorer.Calibrator.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SampleTypesEditor.SomeContainer1.ToggleButton1' at Center.", repo.SampleTypesEditor.SomeContainer1.ToggleButton1Info, new RecordItemIndex(17));
            repo.SampleTypesEditor.SomeContainer1.ToggleButton1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysDesktopExplorer.Control' at Center.", repo.MyAssaysDesktopExplorer.ControlInfo, new RecordItemIndex(18));
            repo.MyAssaysDesktopExplorer.Control.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SampleTypesEditor.SomeContainer1.ToggleButton1' at Center.", repo.SampleTypesEditor.SomeContainer1.ToggleButton1Info, new RecordItemIndex(19));
            repo.SampleTypesEditor.SomeContainer1.ToggleButton1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysDesktopExplorer.Unknown' at Center.", repo.MyAssaysDesktopExplorer.UnknownInfo, new RecordItemIndex(20));
            repo.MyAssaysDesktopExplorer.Unknown.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SampleTypesEditor.SomeContainer1.ToggleButton1' at Center.", repo.SampleTypesEditor.SomeContainer1.ToggleButton1Info, new RecordItemIndex(21));
            repo.SampleTypesEditor.SomeContainer1.ToggleButton1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysDesktopExplorer.Blank' at CenterRight.", repo.MyAssaysDesktopExplorer.BlankInfo, new RecordItemIndex(22));
            repo.MyAssaysDesktopExplorer.Blank.Click(Location.CenterRight);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'SampleTypesEditor.SomeContainer1.ToggleButton1' at Center.", repo.SampleTypesEditor.SomeContainer1.ToggleButton1Info, new RecordItemIndex(23));
            repo.SampleTypesEditor.SomeContainer1.ToggleButton1.MoveTo();
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysDesktopExplorer.Normalizer' at Center.", repo.MyAssaysDesktopExplorer.NormalizerInfo, new RecordItemIndex(24));
            repo.MyAssaysDesktopExplorer.Normalizer.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SampleTypesEditor.SomeContainer1.ToggleButton1' at Center.", repo.SampleTypesEditor.SomeContainer1.ToggleButton1Info, new RecordItemIndex(25));
            repo.SampleTypesEditor.SomeContainer1.ToggleButton1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysDesktopExplorer.Spike' at Center.", repo.MyAssaysDesktopExplorer.SpikeInfo, new RecordItemIndex(26));
            repo.MyAssaysDesktopExplorer.Spike.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
