///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace MyAssaysApp
{
    public partial class ManageTypes1
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void MergedUserCodeMethod1()
        {
        	Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer.Back' at Center.", repo.NewProtocolWizard.SomeContainer.BackInfo);
            repo.NewProtocolWizard.SomeContainer.Back.Click();
        	
        	Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer.AdvancedViewButton' at Center.", repo.NewProtocolWizard.SomeContainer.AdvancedViewButtonInfo);
            repo.NewProtocolWizard.SomeContainer.AdvancedViewButton.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SampleTypesEditor.SomeContainer.AddSampleType' at Center.", repo.SampleTypesEditor.SomeContainer.AddSampleTypeInfo);
            repo.SampleTypesEditor.SomeContainer.AddSampleType.Click();
            
                       
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SampleTypesEditor.SomeContainer1.SomeElement' at Center.", repo.SampleTypesEditor.SomeContainer1.SomeElementInfo);
            repo.SampleTypesEditor.SomeContainer1.SomeElement.Click();

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back 12}'.");
            Keyboard.Press("{Back 12}");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Hello world'.");
            Keyboard.Press("Hello World");

            repo.SampleTypesEditor.SomeContainer1.ToggleButton1.Click();
            repo.MyAssaysDesktopExplorer.Calibrator.Click();
            
            repo.SampleTypesEditor.SomeContainer1.ToggleButton1.Click();
            repo.MyAssaysDesktopExplorer.Control.Click();
      
            repo.SampleTypesEditor.SomeContainer1.ToggleButton1.Click();
            repo.MyAssaysDesktopExplorer.Unknown.Click();
            
			repo.SampleTypesEditor.SomeContainer1.ToggleButton1.Click();
			repo.MyAssaysDesktopExplorer.Blank.Click();
			
			repo.SampleTypesEditor.SomeContainer1.ToggleButton1.Click();
			repo.MyAssaysDesktopExplorer.Normalizer.Click();
			
			repo.SampleTypesEditor.SomeContainer1.ToggleButton1.Click();
			repo.MyAssaysDesktopExplorer.Spike.Click();
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SampleTypesEditor.SomeContainer.SomeContainer' at Center.", repo.SampleTypesEditor.SomeContainer.SomeContainerInfo);
            repo.SampleTypesEditor.SomeContainer.SomeContainer.Click();
            
            repo.MyAssaysDesktopExplorer.SomeElement.Click();
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '50'.");
            Keyboard.Press("{Back 3}");
            Keyboard.Press("50");
                        
           	repo.MyAssaysDesktopExplorer.SomeElement1.Click();
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '150'.");
            Keyboard.Press("{Back 3}");
            Keyboard.Press("150");
            

            repo.MyAssaysDesktopExplorer.SomeElement3.Click();
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '200'.");
            Keyboard.Press("{Back 3}");
            Keyboard.Press("200");
                
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysDesktopExplorer.PARTColorStringEditor' at CenterLeft.", repo.MyAssaysDesktopExplorer.PARTColorStringEditorInfo);
            repo.MyAssaysDesktopExplorer.PARTColorStringEditor.Click(Location.CenterLeft);
            Keyboard.Press("{Delete 10}");
            Keyboard.Press("#FFED0101");
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SampleTypesEditor.SomeContainer1.SomeButton' at Center.", repo.SampleTypesEditor.SomeContainer1.SomeButtonInfo);
            repo.SampleTypesEditor.SomeContainer1.SomeButton.Press();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SampleTypesEditor.SomeContainer.ButtonOK' at Center.", repo.SampleTypesEditor.SomeContainer.ButtonOKInfo);
            repo.SampleTypesEditor.SomeContainer.ButtonOK.Press();
            
           	Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer.Next1' at Center.", repo.NewProtocolWizard.SomeContainer.Next1Info);
            repo.NewProtocolWizard.SomeContainer.Next1.Click();
            
        }
    }
}
