///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyAssaysApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The NewProtocol recording.
    /// </summary>
    [TestModule("2267c2f2-5c6a-4130-83cc-7f36f0cf26af", ModuleType.Recording, 1)]
    public partial class NewProtocol : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyAssaysAppRepository repository.
        /// </summary>
        public static MyAssaysAppRepository repo = MyAssaysAppRepository.Instance;

        static NewProtocol instance = new NewProtocol();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NewProtocol()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NewProtocol Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Program Files (x86)\\MyAssays\\MyAssays Desktop\\MyAssays.Desktop.Explorer.exe' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Program Files (x86)\\MyAssays\\MyAssays Desktop\\MyAssays.Desktop.Explorer.exe", "", "C:\\Program Files (x86)\\MyAssays\\MyAssays Desktop", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Protocols') on item 'MyAssaysExplorer.SomeContainer.Protocols'.", repo.MyAssaysExplorer.SomeContainer.ProtocolsInfo, new RecordItemIndex(1));
            Validate.Attribute(repo.MyAssaysExplorer.SomeContainer.ProtocolsInfo, "Text", "Protocols");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysExplorer.SomeContainer.SomeTabPage' at Center.", repo.MyAssaysExplorer.SomeContainer.SomeTabPageInfo, new RecordItemIndex(2));
            repo.MyAssaysExplorer.SomeContainer.SomeTabPage.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='New ') on item 'MyAssaysExplorer.SomeContainer.New'.", repo.MyAssaysExplorer.SomeContainer.NewInfo, new RecordItemIndex(3));
            Validate.Attribute(repo.MyAssaysExplorer.SomeContainer.NewInfo, "Text", "New ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysExplorer.SomeContainer.New' at Center.", repo.MyAssaysExplorer.SomeContainer.NewInfo, new RecordItemIndex(4));
            repo.MyAssaysExplorer.SomeContainer.New.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='False') on item 'NewProtocolWizard.SomeContainer.CreateMultiplexAssay'.", repo.NewProtocolWizard.SomeContainer.CreateMultiplexAssayInfo, new RecordItemIndex(5));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer.CreateMultiplexAssayInfo, "Checked", "False");
            Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.NewProtocolWizard.SomeContainer.CreateMultiplexAssay, false, new RecordItemIndex(6));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer.OptionMark' at 5;3.", repo.NewProtocolWizard.SomeContainer.OptionMarkInfo, new RecordItemIndex(7));
            repo.NewProtocolWizard.SomeContainer.OptionMark.Click("5;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'NewProtocolWizard.SomeContainer.IWillEnterPasteInMyData'.", repo.NewProtocolWizard.SomeContainer.IWillEnterPasteInMyDataInfo, new RecordItemIndex(8));
            Validate.Exists(repo.NewProtocolWizard.SomeContainer.IWillEnterPasteInMyDataInfo);
            Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.NewProtocolWizard.SomeContainer.Self, false, new RecordItemIndex(9));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Next') on item 'NewProtocolWizard.SomeContainer.Next'.", repo.NewProtocolWizard.SomeContainer.NextInfo, new RecordItemIndex(10));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer.NextInfo, "Text", "Next");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer.Next' at Center.", repo.NewProtocolWizard.SomeContainer.NextInfo, new RecordItemIndex(11));
            repo.NewProtocolWizard.SomeContainer.Next.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Back') on item 'NewProtocolWizard.SomeContainer.Back'.", repo.NewProtocolWizard.SomeContainer.BackInfo, new RecordItemIndex(12));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer.BackInfo, "Text", "Back");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'NewProtocolWizard.SomeContainer.SomeList'.", repo.NewProtocolWizard.SomeContainer.SomeListInfo, new RecordItemIndex(13));
            Validate.Exists(repo.NewProtocolWizard.SomeContainer.SomeListInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'NewProtocolWizard.SomeContainer.SomeList1'.", repo.NewProtocolWizard.SomeContainer.SomeList1Info, new RecordItemIndex(14));
            Validate.Exists(repo.NewProtocolWizard.SomeContainer.SomeList1Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Next') on item 'NewProtocolWizard.SomeContainer.Next'.", repo.NewProtocolWizard.SomeContainer.NextInfo, new RecordItemIndex(15));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer.NextInfo, "Text", "Next");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer.Next' at Center.", repo.NewProtocolWizard.SomeContainer.NextInfo, new RecordItemIndex(16));
            repo.NewProtocolWizard.SomeContainer.Next.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
