///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyAssaysApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SamplesMicroArranged recording.
    /// </summary>
    [TestModule("45ebcfa4-5fee-413b-9381-30909e1455df", ModuleType.Recording, 1)]
    public partial class SamplesMicroArranged : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyAssaysAppRepository repository.
        /// </summary>
        public static MyAssaysAppRepository repo = MyAssaysAppRepository.Instance;

        static SamplesMicroArranged instance = new SamplesMicroArranged();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SamplesMicroArranged()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SamplesMicroArranged Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Program Files (x86)\\MyAssays\\MyAssays Desktop\\MyAssays.Desktop.Explorer.exe' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Program Files (x86)\\MyAssays\\MyAssays Desktop\\MyAssays.Desktop.Explorer.exe", "", "C:\\Program Files (x86)\\MyAssays\\MyAssays Desktop", false);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Select how your samples are arranged. Use an existing layout or create a new one.') on item 'NewProtocolWizard.SomeContainer.SelectHowYourSamplesAreArrangedUs'.", repo.NewProtocolWizard.SomeContainer.SelectHowYourSamplesAreArrangedUsInfo, new RecordItemIndex(1));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer.SelectHowYourSamplesAreArrangedUsInfo, "Text", "Select how your samples are arranged. Use an existing layout or create a new one.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'NewProtocolWizard.SomeContainer.SomeListItem2'.", repo.NewProtocolWizard.SomeContainer.SomeListItem2Info, new RecordItemIndex(2));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer.SomeListItem2Info, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'NewProtocolWizard.SomeContainer.SomeListItem2'.", repo.NewProtocolWizard.SomeContainer.SomeListItem2Info, new RecordItemIndex(3));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer.SomeListItem2Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'NewProtocolWizard.SomeContainer.SomeListItem3'.", repo.NewProtocolWizard.SomeContainer.SomeListItem3Info, new RecordItemIndex(4));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer.SomeListItem3Info, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'NewProtocolWizard.SomeContainer.SomeListItem3'.", repo.NewProtocolWizard.SomeContainer.SomeListItem3Info, new RecordItemIndex(5));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer.SomeListItem3Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'NewProtocolWizard.SomeContainer.SomeListItem'.", repo.NewProtocolWizard.SomeContainer.SomeListItemInfo, new RecordItemIndex(6));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer.SomeListItemInfo, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'NewProtocolWizard.SomeContainer.SomeListItem1'.", repo.NewProtocolWizard.SomeContainer.SomeListItem1Info, new RecordItemIndex(7));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer.SomeListItem1Info, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'NewProtocolWizard.SomeContainer.SomeListItem4'.", repo.NewProtocolWizard.SomeContainer.SomeListItem4Info, new RecordItemIndex(8));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer.SomeListItem4Info, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'NewProtocolWizard.SomeContainer.SomeListItem5'.", repo.NewProtocolWizard.SomeContainer.SomeListItem5Info, new RecordItemIndex(9));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer.SomeListItem5Info, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'NewProtocolWizard.SomeContainer.SomeListItem6'.", repo.NewProtocolWizard.SomeContainer.SomeListItem6Info, new RecordItemIndex(10));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer.SomeListItem6Info, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'NewProtocolWizard.SomeContainer.SomeListItem7'.", repo.NewProtocolWizard.SomeContainer.SomeListItem7Info, new RecordItemIndex(11));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer.SomeListItem7Info, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'NewProtocolWizard.ToggleButton'.", repo.NewProtocolWizard.ToggleButtonInfo, new RecordItemIndex(12));
            Validate.Attribute(repo.NewProtocolWizard.ToggleButtonInfo, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer.SomeContainer1' at 149;107.", repo.NewProtocolWizard.SomeContainer.SomeContainer1Info, new RecordItemIndex(13));
            repo.NewProtocolWizard.SomeContainer.SomeContainer1.Click("149;107");
            Delay.Milliseconds(200);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.NewProtocolWizard.SomeContainer.Self, false, new RecordItemIndex(14));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'NewProtocolWizard.EditButton'.", repo.NewProtocolWizard.EditButtonInfo, new RecordItemIndex(15));
            Validate.Attribute(repo.NewProtocolWizard.EditButtonInfo, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'NewProtocolWizard.SomeContainer.Next1'.", repo.NewProtocolWizard.SomeContainer.Next1Info, new RecordItemIndex(16));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer.Next1Info, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer.Next1' at Center.", repo.NewProtocolWizard.SomeContainer.Next1Info, new RecordItemIndex(17));
            repo.NewProtocolWizard.SomeContainer.Next1.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
