///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyAssaysApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SamplesRackArranged recording.
    /// </summary>
    [TestModule("a9487263-064f-481f-a469-0e008ad371cc", ModuleType.Recording, 1)]
    public partial class SamplesRackArranged : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyAssaysAppRepository repository.
        /// </summary>
        public static MyAssaysAppRepository repo = MyAssaysAppRepository.Instance;

        static SamplesRackArranged instance = new SamplesRackArranged();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SamplesRackArranged()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SamplesRackArranged Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Program Files (x86)\\MyAssays\\MyAssays Desktop\\MyAssays.Desktop.Explorer.exe' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Program Files (x86)\\MyAssays\\MyAssays Desktop\\MyAssays.Desktop.Explorer.exe", "", "C:\\Program Files (x86)\\MyAssays\\MyAssays Desktop", false);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Select how your samples are arranged. Use an existing layout or create a new one.') on item 'NewProtocolWizard.SomeContainer.SelectHowYourSamplesAreArrangedUs'.", repo.NewProtocolWizard.SomeContainer.SelectHowYourSamplesAreArrangedUsInfo, new RecordItemIndex(1));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer.SelectHowYourSamplesAreArrangedUsInfo, "Text", "Select how your samples are arranged. Use an existing layout or create a new one.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Create') on item 'NewProtocolWizard.CreateMultipleLayoutButton'.", repo.NewProtocolWizard.CreateMultipleLayoutButtonInfo, new RecordItemIndex(2));
            Validate.Attribute(repo.NewProtocolWizard.CreateMultipleLayoutButtonInfo, "Text", "Create");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Back') on item 'NewProtocolWizard.SomeContainer.Back'.", repo.NewProtocolWizard.SomeContainer.BackInfo, new RecordItemIndex(3));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer.BackInfo, "Text", "Back");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer.SomeContainer1' at Center.", repo.NewProtocolWizard.SomeContainer.SomeContainer1Info, new RecordItemIndex(4));
            repo.NewProtocolWizard.SomeContainer.SomeContainer1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'NewProtocolWizard.SomeContainer.SomeContainer1'.", repo.NewProtocolWizard.SomeContainer.SomeContainer1Info, new RecordItemIndex(5));
            Validate.Exists(repo.NewProtocolWizard.SomeContainer.SomeContainer1Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Edit') on item 'NewProtocolWizard.EditButton'.", repo.NewProtocolWizard.EditButtonInfo, new RecordItemIndex(6));
            Validate.Attribute(repo.NewProtocolWizard.EditButtonInfo, "Text", "Edit");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Next') on item 'NewProtocolWizard.SomeContainer.Next1'.", repo.NewProtocolWizard.SomeContainer.Next1Info, new RecordItemIndex(7));
            Validate.Attribute(repo.NewProtocolWizard.SomeContainer.Next1Info, "Text", "Next");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeContainer.Next1' at 38;14.", repo.NewProtocolWizard.SomeContainer.Next1Info, new RecordItemIndex(8));
            repo.NewProtocolWizard.SomeContainer.Next1.Click("38;14");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
